name: DCNear
main: me.PimpDuck.DCNear.Main
version: 1.0
commands:
  dcnear:
    description: Gets nearby players
permissions:
  dcnear.god:
    default: op
    description: Allow players to use the /dcnear command for GOD's distance
  dcnear.ub3r:
    default: op
    description: Allow players to use the /dcnear command for Ub3r's distance
  dcnear.legend:
    default: op
    description: Allow players to use the /dcnear command for Legend's distance
  dcnear.super:
    default: op
    description: Allow players to use the /dcnear command for Super's distance
  dcnear.*:
    default: op
    description: Allow players to use the /dcnear [distance] command
    children:
      dcnear.god: true
      dcnear.ub3r: true
      dcnear.legend: true
      dcnear.super: true
